-- yahoo_tokens: stores Yahoo OAuth tokens keyed by session_id.
-- session_id is a UUID generated by the yahoo-proxy edge function and
-- stored in the user's browser localStorage as 'yahoo_session_id'.
-- All reads/writes are performed by the edge function using the service_role key.

CREATE TABLE IF NOT EXISTS public.yahoo_tokens (
  session_id    TEXT PRIMARY KEY,
  access_token  TEXT NOT NULL,
  refresh_token TEXT,
  expires_at    BIGINT,          -- Unix ms when access_token expires
  token_type    TEXT DEFAULT 'Bearer',
  return_url    TEXT,            -- App URL to redirect back to after OAuth
  updated_at    TIMESTAMPTZ DEFAULT NOW()
);

-- No anon or authenticated user access — only the edge function's service_role key
ALTER TABLE public.yahoo_tokens ENABLE ROW LEVEL SECURITY;
CREATE POLICY "yahoo_tokens_deny_all" ON public.yahoo_tokens USING (false) WITH CHECK (false);
